### ISSUE TITLE
How to enable libfdk-aac??

### ISSUE THREAD

**Issue by ls-milkyway** [BtbN/FFmpeg-Builds#145]
Thanks for a good release ....I was always looking for a complete build with support for at-least vmaf & libfdk-aac.

By running ffmpeg -buildconf ....I can see that libfdk-aac is not enabled ...hence I am forced to use  [ffmpeg build by sherpya](https://github.com/sherpya/FFmpeg) ...which allows me to use libfdk-aac by downloading latest dll version & placing it in the same folder.
How can I compile your build with libfdk-acc?? ...so that i don't need to keep 2 ffmpegs....not an expert with compiling part ...I need libfdk-aac both for linux-64 & windows-64.
Do I need to [download dll from sherpya](https://oss.netfarm.it/mplayer/files/libfdk-aac-x86_64-v2.0.2-2-g573e93e.7z) to use it?
Plz suggest.

**Comment by BtbN** [comment]
You need to build the nonfree variant if you want fdk-aac, since that library is not compatible with the GPL, any builds with it enabled cannot be redistributed. Hence you need to produce such a build yourself locally.
Anyone redistributing such builds is in violation of the GPL and should immediately pull those builds down.

**Comment by ls-milkyway** [comment]
> Hence you need to produce such a build yourself locally.

Hmm..,thanks for clarifying....kindly post a link to the best guide to build/compile (cross compile) a non-free version on ubuntu 20.04 LTS  OR If I can use your scripts...what changes do I need to make to enable non-free (of-course I will use it personally not distribute it?

**Comment by BtbN** [comment]
The readme of this very repository should give you all the info you need.
You really just need bash and docker, which is trivial to get on Ubuntu.

**Comment by megapro17** [comment]
You just can fork this repo and enable nonfree builds in .github/workflows/build.yml

**Comment by BtbN** [comment]
Which will make you distribute nonfree builds, which is in violation of the GPL and can get you in legal trouble.
So that is very bad advise.

**Comment by megapro17** [comment]
It's not that clear and perfectly acceptable because it's not a code stealing. Anyway there's a few repos that has binaries so you don't have any risks building it by your own.
https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/OVW25JRWOKOLVMW3XGUX7E4OXFUR2RCG/

**Comment by BtbN** [comment]
Building and using it yourself is not a risk in any way. Offering it for download is.
It's not even about fdk, the build could be without fdk and the issue would still be the same. It's that to build ffmpeg with fdk support, you need to build it in nonfree mode, which makes its binaries non-redistributable no matter what.

Yes, the legal situation regarding fdk is very confusing, but the situation with distributing nonfree builds of ffmpeg is not.

**Comment by ls-milkyway** [comment]
> It's not that clear and perfectly acceptable because it's not a code stealing. Anyway there's a few repos that has binaries so you don't have any risks building it by your own. https://lists.fedoraproject.org/archives/list/legal@lists.fedoraproject.org/thread/OVW25JRWOKOLVMW3XGUX7E4OXFUR2RCG/

You mean fedora has inbuilt ffmpeg with libfdk ....plz provide direct link to the ffmpeg release having libvmaf + libfdk.

**Comment by ValZapod** [comment]
> You mean fedora has inbuilt ffmpeg with libfdk

Yes, they are violating GPL, ffmpeg just does not have enough legal resourses to go after all know parties, including Google and can attract some counter suite in France, LOL.

**Comment by ls-milkyway** [comment]
> ffmpeg just does not have enough legal resourses to go after all known parties, including Google and can attract some counter suite in France,

Holy shi*! ...that induces guilt in me to use it...till they put some solid argument or if they win the suite.

**Comment by BtbN** [comment]
I think the original question is sufficiently answered at this point, so I'll be closing the issue.

**Comment by BasixKOR** [comment]
Since the DLL thing doesn't seem to be answered in this thread I'll leave some info about it here.

sherpya's build is [modified to dynamically load libfdk-aac](https://github.com/FFmpeg/FFmpeg/commit/721ca70f6f8492e7ef6e60c86859a2b5dc12b33b) which circumvents the GPL restriction of 'distributing the GPL code with proprietary binaries'. I think this is quite an elegant solution you may consider.

I'm guessing FFmpeg is unlikely to take this approach upstream since [they don't really want to bring the codecs as DLL](http://ffmpeg.org/faq.html#FFmpeg-does-not-support-codec-XXX_002e-Can-you-include-a-Windows-DLL-loader-to-support-it_003f).
