### ISSUE TITLE
Question: Hardware encoding with AV1 and FFmpeg

### ISSUE THREAD

**Issue by benpar2** [BtbN/FFmpeg-Builds#162]
Hello.
Recently Intel released the new GPU series, Intel Arc, that supports hardware encoding of AV1. They claim its speed 50 times faster than software encoding. I’d like to know is it available on FFmpeg? If yes, how can we use it?
I would appreciate your answer.

**Comment by BtbN** [comment]
Probably via their OneAPI, any likely also vaapi, if I had to guess.
Haven't seen it in QSV yet. Better ask this on ffmpeg-user, since it's otherwise unrelated to these builds.
At least I'm not aware of anything I'd have to add for support.
Feel free to re-open if it turns out to be a missing dependency after all.
