### ISSUE TITLE
Feature request: Add kvazaar support

### ISSUE THREAD

**Issue by cowsaysfoo** [BtbN/FFmpeg-Builds#173]
Any chance of a build with external libraries, specifically kvazaar HEVC encoder (https://github.com/ultravideo/kvazaar)? 
Instructions for compiling libkvazaar with ffmpeg seem kinda thin and technical (at least for those of us not at all experienced in compiling ffmpeg and external libraries for windows from scratch...like...me :/ ), but supposedly it's entirely possible.

**Comment by BtbN** [comment]
I mean, statically building in external libraries is the whole point of 
this repo :D
Adding an additional library is usually no big issue, if it's reasonable 
and non-broken.

Pull-Requests for additions are always welcome, since I right now don't 
have time to figure out new builds.
So it could take a while until I get to it, since there's a few other 
libraries on the list.
