### ISSUE TITLE
Flag FFmpeg as DPI Aware on Windows

### ISSUE THREAD

**Issue by EwanGreen4** [BtbN/FFmpeg-Builds#177]
Hello. Currently in FFmpeg there is a bug related to cursor scale (or sometimes placement) on certain video sources when any DPI scaling is present. Since every common build of FFmpeg has no specification of DPI awareness, Windows assumes that the app is *not* DPI aware and will scale geometry accordingly. This is helpful in most situations, since it means that GUI apps will be scaled automatically and it'll be a cheap & easy fix (if a bit ugly).

This affects FFmpeg adversely since the cursor is also scaled, and results in improper size of the fake cursor. I wouldn't be surprised if it introduced other bugs I don't know of as well. 
In ShareX's screen-capture-recorder video source, this affects cursor position as well (even worse!).

The fix is very simple and [has been proposed in ffmpeg's bug tracker before](https://trac.ffmpeg.org/ticket/4505), but it's never been fixed. I was wondering if you could apply such a change for your builds by using an embedded app manifest. It would look something like this:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
  <asmv3:application>
    <asmv3:windowsSettings>
      <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true</dpiAware>
    </asmv3:windowsSettings>
  </asmv3:application>
</assembly>
```

**Comment by BtbN** [comment]
I am avoiding applying any kind of patches to ffmpeg itself, since it's 
very prone to random breakages and makes building alternate repositories 
very hard.

If there was a patch submitted but forgotten, feel free to ping it.
I'm very much in favour of including it.

On that note, check out the ddagrab filter I recently added to ffmpeg.
It should vastly outperform gdigrab (specially when directly fed to a 
hardware encoder without download from GPU) and I believe it handles all 
those DPI scaling issues internally (by completely ignoring scaling 
exists, pretty much).

**Comment by EwanGreen4** [comment]
Thanks for your response. I personally wouldn't think of it as a patch -- it's more of a way to specify behavior that Windows assumes of a program. It's more future-proof than a traditional patch and would be applied post compile-time; either in the linking step or with mt.exe afterwards. It would also fix more than just gdigrab; since it applies to the whole program, it propagates to all loaded libraries and would work with, say, screen-capture-recorder as well. Just food for thought

**Comment by Jaex** [comment]
In 2014, we started using FFmpeg to accomplish both screen recording and encoding in [ShareX](https://github.com/ShareX/ShareX). There were always high DPI related issues (in both GDI grab and DirectShow devices). Though these issues were reported in the FFmpeg issue tracker a long time ago, the problems were never fixed; I couldn't fix it because I don't have any experience with C++. At this point, we had no chance but find workaround. The best we could find was adding a manifest to ffmpeg.exe (with the `dpiAware` element set to `true`) using [mt.exe](https://docs.microsoft.com/en-us/windows/win32/sbscs/mt-exe). Both GDI grab and DirectShow devices were then working properly at a high DPI. Instead of manually adding the manifest to ffmpeg.exe and hosting it ourselves, we thought it would be beneficial to everyone if you could include a manifest in your builds via. CI, that way everyone would benefit from it.

I agree that it would be better if these high DPI issues were solved upstream, but that's not an option so I think this is a good middle ground.

> I am avoiding applying any kind of patches to ffmpeg itself

I don't think it's necessarily considered patching because you don't have to modify anything in the compiling process and you can just add the manifest file to an already compiled FFmpeg executable as CI step.

**Comment by BtbN** [comment]
Adding a manifest to the fftools is not hard.
But it has to be done upstream, not in this repo. If there's a patch on the ML and it was ignored, please ping it.

**Comment by EwanGreen4** [comment]
[This](https://trac.ffmpeg.org/ticket/4232) would be the ticket to bump. The one I posted was marked as a dupe.

**Comment by BtbN** [comment]
Bumping a ticket doesn't achieve much.
A Patch on the ML does.

**Comment by EwanGreen4** [comment]
I guess I don't know what you mean by ML.

**Comment by sylveon** [comment]
Mailing list

**Comment by Jaex** [comment]
> check out the ddagrab filter I recently added to ffmpeg

Hi @BtbN, thanks for ddagrab support!

I implemented it to our app now: https://github.com/ShareX/ShareX/commit/03e83ae2405b223d808dae1b9d3d82c3d83ede6d

![](https://jaex.getsharex.com/2023/07/ShareX_o0rZs42Xoz.png)

But because I don't have multi monitors, I asked help in our Discord server and first person tested it had a lot of issues.
Main problem was his monitors were portrait and recording rotated incorrectly:
ddagrab = https://cdn.discordapp.com/attachments/286227439343108096/1126885629662339202/DiscordPTB_wFlTdDLyu3.mp4
gdigrab = https://cdn.discordapp.com/attachments/286227439343108096/1126889200529178706/DiscordPTB_A9m7YCNDOF.mp4

Then somehow size was randomly showing wrong and failing:
https://jaex.getsharex.com/2023/07/o4GvEzwIbr.png
gdigrab works fine in all situations so I assume this issues are related to ddagrab.

I know here is not correct place to talk about ffmpeg related issues, we can talk in Discord if you want and hopefully our user can give more reproduce steps.
