### ISSUE TITLE
It doesn't work properly on my Windows 7 computer

### ISSUE THREAD

**Issue by 123rui** [BtbN/FFmpeg-Builds#18]
Hello, I have written a small piece of software in Python. It works on my Win10 computer, but it doesn't work when it is downloaded to my Win7 computer. Why is that?An error is as follows

![a](https://user-images.githubusercontent.com/26771382/97300185-136a7300-1891-11eb-8fec-cd3849b1823d.png)

The FFMPEg-related EXE file I downloaded was placed in a directory of the EXE file I packaged. May I ask what problem caused it to be unavailable?

**Comment by BtbN** [comment]
I can't really help you debug your Python library.
Nothing in that screenshot (of plain text, which I thus cannot even copy) indicated an issue with anything but Python code.

The ffmpeg binaries are built with a minimum Windows Version of 0x0601 which according to Microsoft is Windows 7.
If some of the libraries used have dropped Windows 7 support, there is not much I can do about that.
Windows 7 is long past its intended lifespan, and I won't do any major effort to support it.

Please show the actual issue Windows 7 has with it, not some otherwise unrelated Python-Backtrace.
