### ISSUE TITLE
How to use new gcc x86-64-v3 instruction

### ISSUE THREAD

**Issue by CharlesMengCA** [BtbN/FFmpeg-Builds#192]
Hi, 

Could you let me know how to use x86-64-v3 gcc instruction for the win64 build?

Thanks

**Comment by BtbN** [comment]
What do you mean, use x86-64-v3 instructions?
FFmpeg dynamically detects the CPU capabilities and uses the respective available hand-optimized assembly.

**Comment by ZaquL** [comment]
It is widely known lihux kernel uses -O2. Which is of course just wrong, and strange coming from Linus who literally submits reports to gcc bugzilla every month. He should know better. It will be more obvious when PREEMT_RT will be merged, instruction pressure will be bad.

Same here, v3 is AVX 256, v4 is AVX 512. You can see it on wikipedia, on x86_64 history, which is so complex. The fact is new tech from gcc like new float16 mode is done by you, so you know what is this all about.

Lynee also tried to do automatic vectorisation. And some other guy wanted to turn on -O3, the only thing that is needed is disabling one mostly assembly file for AVC and all HEVC CABAC. Bug in gcc, though.

See how v3 is activated here: https://github.com/zhongfly/mpv-winbuild/commit/c70bf9f74d7d3cba3d53393f3274dc8ae5c0e5b2

Maybe that is what microsoft was planning when they tried strange limitation on windows 11 and certainly what MacOS on M1 was doing, it did confuse clang people, since they were really late for optimisation in their instruction scheduler for M2. Anyway...

Of course, it is also very funny what you will do when armv9 will become mainstream (Galaxy S22 Snapdragon gen 1 is first to support it, if OS supports it that is). I mean mpv that is compiled for Snapdragon 845 (it has new arm8.x arch) and destributed for reddit. I installed it on Galaxy S21 FE but on old devices it does not work.

**Comment by BtbN** [comment]
If you want to pass that -march, there is very little point to it.
It would drastically reduce the compatibility of the binaries, for very little or no real world gains.
The heavy lifting of CPU bound code is almost entirely done in hand written assembly, so I'm not at all a fan of the idea of reducing binary compatibility for little to no gain.

**Comment by ZaquL** [comment]
Actually linux kernel removed support from architecture arc: https://github.com/torvalds/linux/commit/a6036a41bffba3d5007e377483b425d470ad8042

So I guess Linus did make it happen.

**Comment by BtbN** [comment]
I have no idea what you are all going on about. Everything brought up here is entirely unrelated to anything else.
So I'm just gonna close the issue here.

Assuming the original issue was to bump the -march of the builds to x86-64-v3: Not gonna do that, that'll pointlessly reduce compatiblity.
