### ISSUE TITLE
Get an strange HTTPS error when craw https stream.

### ISSUE THREAD

**Issue by lifegpc** [BtbN/FFmpeg-Builds#21]
![image](https://user-images.githubusercontent.com/41434272/97325016-7bc74d80-18ad-11eb-8489-be9e0df5bb9d.png)
zeranoe's build works fine.
System is windows 10.

**Comment by BtbN** [comment]
Zeranoes build were using gnutls, while this is using Windows schannel.
Does it work with any other domain?

**Comment by lifegpc** [comment]
I try another domain. Works fine.

**Comment by lifegpc** [comment]
The [download tools](/lifegpc/bili/tree/dev) I used.

**Comment by lifegpc** [comment]
> ![image](https://user-images.githubusercontent.com/41434272/97325016-7bc74d80-18ad-11eb-8489-be9e0df5bb9d.png)
> zeranoe's build works fine.
> System is windows 10.

This link should have broswer's UA and a correct referer, may cause this problem?

**Comment by BtbN** [comment]
Then it's not an issue with ffmpeg or this build, but Windows does not like the security of that specific Domain.
It's failing way before even getting to HTTP messages.
Does Internet Explorer or Edge open the domain?

In any case, the error reporting on this could probably be a bit better, so you could open an issue on ffmpeg trac about it.
But it's not something I can in any way fix on these builds, so closing the issue here.

**Comment by lifegpc** [comment]
OK.
