### ISSUE TITLE
mbedtls doesn't work with rtmps

### ISSUE THREAD

**Issue by atyachin** [BtbN/FFmpeg-Builds#232]
Issue: current ffmpeg build can't output to rtmps endpoints. An error occurs on connection:
mbedtls_ssl_read reported connection reset by peer

Resolution:
Switch to gnutls or openssl libraries - tested and work.

**Comment by BtbN** [comment]
Both of those are unfortunately not an option due to the license situation, and gnutls does not play nice with static linking and has a heapload of dependencies that makes it extremely bothersome to add and support.

So you should raise this issue upstream with ffmpeg and/or mbedtls to get it fixed.

**Comment by atyachin** [comment]
Is openssl also a problem from licensing perspective?

I can raise this with the ffmpeg devs, but for the time being, your build doesn't support rtmps...

**Comment by BtbN** [comment]
Yes, OpenSSL 1.1.1, which is still required by a bunch of other dependencies, has a not GPL compatible license, so cannot be statically linked with FFmpeg in redistributable builds.
With OpenSSL 3.0 the license is changed and it's no longer an issue, but other things depending on openssl are still not ready for it.
mbedtls is the only workable library I've found. And rtmps really should work with it, there is no reason why it wouldn't, so the issue needs fixed no matter what.
