### ISSUE TITLE
Don't create named subdir in archive 

### ISSUE THREAD

**Issue by mimi89999** [BtbN/FFmpeg-Builds#26]
Hello,
I saw that in 825a74c1adcc504d7491c17fc6b2c0cf0654d573 you added the creation of named subdir in the archive. Why? This makes automatic installs with https://just-install.github.io/ impossible. Could you please revert to not adding the named zip in the archive or make the name of that folder stable (like `ffmpeg`)?

**Comment by BtbN** [comment]
If you have multiple archives next to one another, having all of them contain an identical file structure would cause a mess if you unpack all of them. It would also make it very hard to identify the version of the unpacked directory tree.
It's also bad practice to have files in an archive without a top level subdir, since extracting then pollutes your working dir.

Why can't you just deduce the directory name from the filename? Just strip the extension, and you got the directory inside of the zip.

But in any case, at this point it is too late to change packaging details like that, since there is a high chance other automated tools have started using the zipfiles. So changing their structure in an incompatible way is out of question.
