### ISSUE TITLE
Feature Request: Enabling VA-API for Windows builds

### ISSUE THREAD

**Issue by ghost** [BtbN/FFmpeg-Builds#260]

**Comment by BtbN** [comment]
As far as I'm aware that's for VAAPI in WSL, as in, for Linux-Builds, which have VAAPI enabled anyway.
Windows-Builds already have plenty of options for hardware-acceleration, so adding vaapi seems entirely pointless.

**Comment by BtbN** [comment]
There are patches for d3d12va stuff on the list since a while, and being worked on. Same for Vulkan.
From what I read about this vaapi wrapper, it's rather suboptimal, performance wise.
It also seems like a massive hassle. I'd have to not only build libva, but also the entirety of mesa.
And libva on Linux has already demonstrated to be extremely hard to link statically (the state of vaapi on Linux is half-broken due to that, your OS has to have matching versions of libva installed, or it just crashes).
I haven't looked at mesa yet, but I'd imagine it's even less built with static linking in mind.

So I'd really much rather wait for d3d12 or vulkan stuff to land, if you really want a vendor neutral encoder that badly.
In the meantime, the various encoders are all accessible via their native API.

**Comment by BtbN** [comment]
Using a prebuilt package is against the very idea of this repo.
So are you saying one does not need mesa after all, and it somehow comes with Windows now?
Cause I only see it building libva there.

The main issue with statically linking libva isn't libva itself. It's that libva is just a very thin shim that at runtime dynamically loads its drivers. Statically linking those drivers is not possible for all I'm aware. And the ABI between shim and drivers is not stable.
So if there is a mismatch between the statically linked libva, and the drivers it finds on the OS, various bad things happen.

**Comment by BtbN** [comment]
If that's how it works, I don't see inclusion of it happening.
That is VERY counter-intuitive and not something the average user will do or be able to figure out. It'll cause more Github-issues about "Why is this crashing?" or "Why does this not work?".
It either has to work out of the box after downloading the binary, or it's a bad idea to include.

**Comment by BtbN** [comment]
That's also major difference with AMF, Nvenc and so on. The driver offers a stable ABI, and will not just randomly change it.
