### ISSUE TITLE
Very confusing for people who aren't software developers

### ISSUE THREAD

**Issue by lukeflegg** [BtbN/FFmpeg-Builds#283]
Am I the only one here who knows people who'd love to use ffmpeg but aren't massive nerds like us?
Even I find it a faff to
1. Find the link to actually download ffmpeg (compare to any other app online)
2. Work with the obscure archive file format (can we just use a normal .zip? or even better just a simple .exe everyone knows what to do with?)
3. If we really do have to have an archive they have to extract, then why on earth is the exe file buried in an obscure folder structure "bin, doc, include, lib?" I mean seriously. The amount of genius that's gone into making this software, undermined by the amount of disconnect from ordinary people who aren't software developers.. surely we want more people to be able to make use of this software? This is the easy bit to get right isn't it?

**Comment by Nevcairiel** [comment]
I'm sorry you are having trouble finding everything.

However, I must note that the downloads are quite similar to many other GitHub projects, just click on Releases and grab the files from the top most version. Find the one suiting your environment - Windows I assume, and get it ("win64" is a common short hand for Windows 64-bit)

The Windows version is even in a .zip file for easy unpacking. The other archive formats are for the Linux versions of FFmpeg. We do service a wide array of operating systems, after all, not just Windows.

The files being structured in a meaningful way seems reasonable to me. You don't want documentation and development files intermingling with the executables. That would just be total mayhem.

**Comment by garoto** [comment]
I wonder what the odds are of someone who are struggling with any of your points to be able to actually use ffmpeg to begin with.

**Comment by BtbN** [comment]
If you are struggling with the archive format, you likely downloaded a version that's not for Windows.
The windows builds are all in zip archives, precisely because Windows can unpack it natively (it actually wastes quite a bit of space, zip is super inefficient compared to anything else).

And I'm honestly not sure what to make of most of your points. FFmpeg consists out of multiple executable, and their accompanying documentation. Putting them together in an archive is by far the easiest way to distribute them.
Also, to use ffmpeg, some advanced "nerd" knowledge is unavoidable. It's a command line application, with a very involved syntax to make it do things.

Are you maybe looking for Handbrake or similar tools, that are more geared towards end users?
FFmpeg itself is by its nature very developer-centric.

**Comment by coronacharly** [comment]
Maybe what you are looking for is aTube Catcher with a graphical interface

>

**Comment by garoto** [comment]
I see the chink reaction-emoji train is getting stronger every day now...

**Comment by ArchemedIan** [comment]
1. this is literally the easiest way to build ffmpeg, with HW accel, I've ever used in my life. docker, and these scripts, are a friggen miracle as far as I'm concerned, let alone the magical ffmpeg itself. if they can not figure this out, to put it simply, they are not worthy of its magesty. if docker is installed, its literally like 2 or three commands. 

2. _my brother in Christ_ you are literally on github.com, you are aware of that, correct? that this site, is literally,


## FOR. SOFTWARE. DEVELOPERS
