### ISSUE TITLE
Add builds for linux armv6 (armel) and linux armv7 (armhf) ?

### ISSUE THREAD

**Issue by jidckii** [BtbN/FFmpeg-Builds#286]
Do you have any plans to add builds for **armv6** (armel) and **armv7** (armhf) ?
We have all the necessary tools for this already in the Ubuntu repositories

```
    crossbuild-essential-arm64
    crossbuild-essential-armel
    crossbuild-essential-armhf
```

Now I'm using builds from https://johnvansickle.com/ffmpeg/ but [problems started](https://gitlab.com/yuccastream/yucca/-/issues/1058)  on debian 12, apparently due to the old environment when building like gcc and other things.
I like your project and I'm ready to help in the implementation, but I don't see instructions for contributors and therefore I don't know where to start.

**Comment by BtbN** [comment]
I don't plan on extending the current selection of architectures, except for adding windows-aarch64 whenever I find a way to ct-ng a toolchain.
Adding it to the build setup shouldn't be too hard, crosstools-ng support it fine, but it's going to be a lot of work to get it right, and it will be very slow (all the optimization work and testing is done on aarch64).
It'll also add a lot of clutter to a lot of the build scripts, since I'm sure it won't be all that well tested.
