### ISSUE TITLE
Builds for win32 and pdb

### ISSUE THREAD

**Issue by 29654761** [BtbN/FFmpeg-Builds#3]
Will you plan to build for win32 and offer pdb files
Those are really important to me.
Think you!

**Comment by BtbN** [comment]
I have no plans of adding 32 bit builds, 64bit is the standard for over a decade at this point.

Also, the builds are using gcc, not MSVC, so there cannot be pdb files, since gcc does not generate any.
I also don't plan adding the _g variant of the binaries, simply because of their enormous size.

The current builds are already closing in on the asset size limit of Github. That and the already quite long list of variants does not need to get even more complicated for very niche use cases.

I can add the ability to build 32bit variants to the scripts, but I will not add that to the autobuilds.
PDB is simply not possible, because it's a gcc build.

**Comment by Fierelier** [comment]
I would love the ability to build 32bit variants.

**Comment by BtbN** [comment]
The ability to build 32 bit variants was added with the commit that closed this issue.
But there won't be auto-builds for it. And a lot of packages and features do not work with it, because the dependencies in question dropped 32 bit support.

I'd strongly encourage everyone to use 64bit in the year of 2020.

**Comment by Mikasa-san** [comment]
https://www.videohelp.com/software/ffmpeg/old-versions

**Comment by Fierelier** [comment]
> 
> 
> a lot of packages and features do not work with it, because the dependencies in question dropped 32 bit support.

I am sick and tired of 32bit deprecation. Thank you though for making the best of it.

> 
> I'd strongly encourage everyone to use 64bit in the year of 2020.

I see why, but honestly 32bit CPUs are not worth deprecating, especially with programs that can hold realistic workloads for those chips. They are very powerful given the right software, the weakness tends to be the software optimization or lack of optimizations in the software's content (**cough** most of today's websites). A lot of developers have the mindset of "well barely anyone uses it, so it's not worth maintaining", and I honestly think that is just wrong because they're wasting potential for comfort.

You can make the argument that these CPUs are less friendly to the environment, as they deliver less performance per watt, but I think that won't be an aspect forever. I'm a firm believer that solar energy will replace most of our current, conventional energy.

Just making sure we understand: this is not an attack against you, @BtbN, you didn't break it. Thanks again.

**Comment by BtbN** [comment]
You can't really blame the software for it either.
When you have limited developer resources, you'd rather have them write hand-optimized assembly for the architecture the majority of people use.
On top of that, pure x86 without any of the 64bit and vector extensions is nearly impossible to write performant code for.
Pretty much all the dependencies it affects are modern codecs (HEVC and AV1 exclusively even), where just no software path exists.
No matter how hard anyone would try, 32 bit is too limited due to low register count and lack of modern vector extensions.
FFmpeg itself also falls back to pure C code in a lot of those cases, severely hurting performance.

By now, even the cheapest of the cheapest modern CPU will easily outperform whatever old 32 bit box you still have standing there, and will probably be more energy efficient at it. Even for things where 32 bit still works.

**Comment by Fierelier** [comment]
> When you have limited developer resources, you'd rather have them write hand-optimized assembly for the architecture the majority of people use.

From a money standpoint you'd be right, obviously, maintaining 32bit is not worth it. I just wish money didn't rule the world as it did, though I won't open that can of worms.

> No matter how hard anyone would try, 32 bit is too limited due to low register count and lack of modern vector extensions.

I am not expecting them to magically summon fast code on this old architecture, I see that this is not always possible because of the missing extensions and what have you. I'd just rather it'd not just die out. Many times it is for the wrong reasons.

> even the cheapest of the cheapest modern CPU will easily outperform whatever old 32 bit box you still have standing there

You're right, but again, if you look at many 32 bit processors alone, they are technically strong enough for a majority of tasks that many would want to do, they definitely were in the past, back when software was more sane. Newer processors certainly are technically way faster and I do think they are useful in new ways, but I think their fast performance is way too relied upon for too many regular tasks.

Thank you for the well-crafted response.

**Comment by codeoflin** [comment]
I made a media application with ffmpeg and my boss just let me to run it on a 32bit system
