### ISSUE TITLE
When building the debug version yourself, qsv is missing

### ISSUE THREAD

**Issue by mycrl** [BtbN/FFmpeg-Builds#384]
```sh
./makeimage.sh win64 nonfree-shared 4.4 debug
```

Using ffmpeg -codecs does not list h264_qsv

**Comment by BtbN** [comment]
libvpl is only supported since ffmpeg 6.0, so versions older than that won't be built with the qsv stuff enabled, debug or not.

**Comment by mycrl** [comment]
> libvpl is only supported since ffmpeg 6.0, so versions older than that won't be built with the qsv stuff enabled, debug or not.

@BtbN But I used the ffmpeg4.4 build product in your release, and h264_qsv exists

**Comment by BtbN** [comment]
That must have been _really_ old then. Intel has since abandoned the old libmfx, and it's not safe to use the old library anymore, for numerous unfixed potentially security relevant issues.
Only libvpl is supported by Intel now. And only ffmpeg 6.0 and up support libvpl.
In the past, when libmfx was still supported, 4.4 did support qsv.
