### ISSUE TITLE
Is there a nonfree version available for download?

### ISSUE THREAD

**Issue by xengine-qyt** [BtbN/FFmpeg-Builds#431]
I can't find where to download it.i need fdk_aac lib support

**Comment by BtbN** [comment]
The whole thing with nonfree builds is that they can't be redistributed.
So if you want one, you need to build it yourself.

**Comment by xengine-qyt** [comment]
> The whole thing with nonfree builds is that they can't be redistributed. So if you want one, you need to build it yourself.

how to build this 
ubuntu22.04.5

sudo ./build.sh win64 nonfree-shared 6.1

report error:

```
+ shopt -s globstar
++ dirname ./build.sh
+ cd .
+ source util/vars.sh
++ [[ 3 -lt 2 ]]
++ TARGET=win64
++ VARIANT=nonfree-shared
++ shift 2
++ [[ -f variants/win64-nonfree-shared.sh ]]
++ LICENSE_FILE=COPYING.LGPLv2.1
++ ADDINS=()
++ ADDINS_STR=
++ [[ 1 -gt 0 ]]
++ [[ -f addins/6.1.sh ]]
++ ADDINS+=("$1")
++ ADDINS_STR=6.1
++ shift
++ [[ 0 -gt 0 ]]
++ REPO=btbn/ffmpeg-builds
++ REPO=btbn/ffmpeg-builds
++ REGISTRY=ghcr.io
++ BASE_IMAGE=ghcr.io/btbn/ffmpeg-builds/base:latest
++ TARGET_IMAGE=ghcr.io/btbn/ffmpeg-builds/base-win64:latest
++ IMAGE=ghcr.io/btbn/ffmpeg-builds/win64-nonfree-shared-6.1:latest
+ source variants/win64-nonfree-shared.sh
+++ dirname variants/win64-nonfree-shared.sh
++ source variants/win64-gpl-shared.sh
++++ dirname variants/win64-gpl-shared.sh
+++ source variants/windows-install-shared.sh
++++ dirname variants/win64-gpl-shared.sh
+++ source variants/defaults-gpl-shared.sh
+++++ dirname variants/defaults-gpl-shared.sh
++++ source variants/defaults-gpl.sh
+++++ FF_CONFIGURE='--enable-gpl --enable-version3 --disable-debug'
+++++ FF_CFLAGS=
+++++ FF_CXXFLAGS=
+++++ FF_LDFLAGS=
+++++ GIT_BRANCH=master
+++++ LICENSE_FILE=COPYING.GPLv3
++++ FF_CONFIGURE+=' --enable-shared --disable-static'
++ FF_CONFIGURE='--enable-nonfree --enable-gpl --enable-version3 --disable-debug --enable-shared --disable-static'
+ for addin in ${ADDINS[*]}
+ source addins/6.1.sh
++ GIT_BRANCH=release/6.1
+ docker info -f '{{println .SecurityOptions}}'
+ grep rootless
+ UIDARGS=(-u "$(id -u):$(id -g)")
++ id -u
++ id -g
+ rm -rf ffbuild
+ mkdir ffbuild
+ FFMPEG_REPO=https://github.com/FFmpeg/FFmpeg.git
+ FFMPEG_REPO=https://github.com/FFmpeg/FFmpeg.git
+ GIT_BRANCH=release/6.1
+ GIT_BRANCH=release/6.1
++ mktemp
+ BUILD_SCRIPT=/tmp/tmp.gJ9bvIIBtS
+ trap 'rm -f -- '\''/tmp/tmp.gJ9bvIIBtS'\''' EXIT
+ cat
+ [[ -t 1 ]]
+ TTY_ARG=-t
+ docker run --rm -i -t -u 0:0 -v /home/ubuntu/FFmpeg-Builds/ffbuild:/ffbuild -v /tmp/tmp.gJ9bvIIBtS:/build.sh ghcr.io/btbn/ffmpeg-builds/win64-nonfree-shared-6.1:latest bash /build.sh
Unable to find image 'ghcr.io/btbn/ffmpeg-builds/win64-nonfree-shared-6.1:latest' locally
docker: Error response from daemon: Head "https://ghcr.io/v2/btbn/ffmpeg-builds/win64-nonfree-shared-6.1/manifests/latest": denied.
See 'docker run --help'.
+ rm -f -- /tmp/tmp.gJ9bvIIBtS
```

**Comment by BtbN** [comment]
You need to make the image first, with the respective makeimage.sh script.
Since nonfree stuff is not redistributable, neither are the images.

**Comment by rob1121** [comment]
WARNING: local cache import at .cache/ghcr.io/btbn/ffmpeg-builds/base_latest not found due to err: could not read .cache/ghcr.io/btbn/ffmpeg-builds/base_latest/index.json: open .cache/ghcr.io/btbn/ffmpeg-builds/base_latest/index.json: The system cannot find the file specified.
+ mkdir -p /c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base
+ docker image save ghcr.io/btbn/ffmpeg-builds/base:latest
+ tar -x -C /c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base
+ IMAGE_TARGET=/c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base-win64
+ [[ ! -d /c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base-win64 ]]
+ docker buildx --builder ffbuilder build --cache-from=type=local,src=.cache/ghcr.io/btbn/ffmpeg-builds/base-win64_latest --cache-to=type=local,mode=max,dest=.cache/ghcr.io/btbn/ffmpeg-builds/base-win64_latest --build-arg GH_REPO=ghcr.io/btbn/ffmpeg-builds --build-context ghcr.io/btbn/ffmpeg-builds/base:latest=oci-layout:///c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base --load --tag ghcr.io/btbn/ffmpeg-builds/base-win64:latest images/base-win64
[+] Building 0.0s (0/0)                                                                                                                                 docker-container:ffbuilder
ERROR: oci-layout reference "oci-layout:///c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base" could not be resolved: could not lock /c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base/index.json.lock: open /c/Users/MONARK/dev/FFmpeg-Builds/.cache/images/base/index.json.lock: The system cannot find the path specified.
+ rm -f /tmp/tmp.1G34saknDG.toml
