### ISSUE TITLE
Linux, Mac OS and Android Builds?

### ISSUE THREAD

**Issue by JezSonic** [BtbN/FFmpeg-Builds#55]
Just asking about support for Linux, Mac OS and Android Builds

**Comment by BtbN** [comment]
There are already static builds for Linux available from https://johnvansickle.com/ffmpeg/
So I decided to put more of the available asset size limit towards Windows variants instead of Linux.

For OSX there is no way to dockerize a build environment, since Docker does not support OSX, and neither is there any properly working and supported Cross-Toolchain I could install on Linux to make OSX builds.

There's also https://evermeet.cx/ffmpeg/ linked on the ffmpeg.org homepage, but I never tested any of those, since I don't care about Apple stuff.

**Comment by JezSonic** [comment]
I know about the static builds but i don't need them. I need dynamic llibrary files like .so and .dylib.

For OSX Toolchain this can be used to compile toolchains on linux https://github.com/tpoechtrager/osxcross - works with ffmpeg building. I'll fork this repo and try adding linux builds for myself

**Comment by BtbN** [comment]
I tries using that toolchain, and it failed to build the majority of the dependencies because the build systems got confused about what's going on.
Adding Linux-Builds should be fairly straight forward, but I'm not sure what the point of that is for Linux. Every distro has ffmpeg packaged.

**Comment by sudo-nautilus** [comment]
> I know about the static builds but i don't need them. I need dynamic llibrary files like .so and .dylib.
> 
> For OSX Toolchain this can be used to compile toolchains on linux https://github.com/tpoechtrager/osxcross - works with ffmpeg building. I'll fork this repo and try adding linux builds for myself

There's one for Android ( libffmpeg.so - is that what you want ? ), I guess

**Comment by sudo-nautilus** [comment]
`FFplay` cannot be compiled for Android, because it can't display the play window on mobile phones. But `FFprobe` and `FFmpeg` can be compiled for Android

**Comment by cdgriffith** [comment]
> Adding Linux-Builds should be fairly straight forward, but I'm not sure what the point of that is for Linux. Every distro has ffmpeg packaged.

I would throw in a vote for you to have Linux builds, as yours have the three main AV1 encoders which I haven't found for any of the other static builds. The packaged versions are also way out of date in many cases.

**Comment by BtbN** [comment]
I've been looking into that the last couple days actually, and it's surprisingly painful.
Main issue is glibcs inability to actually be linked statically, so you end up with static builds that only work on super bleeding edge systems that use the same or newer of a glibc than your build system.
Looked into using musl, but getting a toolchain for that going is a) a pain and b) takes several hours of build time. And I'd also expect a lot of random issues caused by musl not being glibc.

**Comment by BtbN** [comment]
Linux builds are now a thing. The dynamic linking situation on Linux makes this whole thing into quite a mess. The purely static binaries should work mostly okay anywhere.
The resulting fully static binaries should in theory also run on Android.
Shared builds are a bit of a mess, and were quite broken in my tests. I'm leaving them in for now, but if any major issues come up, they will be discontinued.
It's virtually impossible to have fully static "shared libs" alongside having programs that only need those libs.
With glibc, you run into a situation where your dynamic binaries won't run on a system with even a slightly older glibc.
So I opted for Alpine with musl, but as a result, any dynamic binaries need musl installed to even run. Severely limiting the usefulness of the binaries.

Other than that, I don't see a sane way to implement anything like "Android builds". I'm not gonna develop an App for it, and the multitude of devices and versions makes it a nightmare to deal with.

For OSX, there is no sane way to build for and support all the various arches either. On top of that, there is no proper cross compiler, and no way to test the resulting binaries for me. So unless something about this changes, or someone comes up with a sane way to implement support, I won't be supporting OSX.

**Comment by cdgriffith** [comment]
Not sure if it would work on github actions, but can do Mac OSX dockerization now https://github.com/sickcodes/Docker-OSX
