### ISSUE TITLE
Description of builds

### ISSUE THREAD

**Issue by anaveem** [BtbN/FFmpeg-Builds#57]
Hi
No matter how tech-savvy they are, I don't think most users understand the difference between all these builds.
Can you please provide some description of the differences between them? in the Wiki would be good. 

thanks

**Comment by sudo-nautilus** [comment]
They are basically based on licenses and variants,

**Comment by anaveem** [comment]
Ok, good to know, but what does that mean to the average user? How do they know which to download? Do they all work exactly the same? This is what I'm trying to get at. thanks

**Comment by sudo-nautilus** [comment]
> Ok, good to know, but what does that mean to the average user? How do they know which to download? Do they all work exactly the same? This is what I'm trying to get at. thanks

The General Public License one (GPL) is what I recommends

**Comment by sudo-nautilus** [comment]
Eg : Win64-gpl

**Comment by necros2k7** [comment]
ffmpeg-n4.3.2 and ffmpeg-N-101626 what`s the difference which branch is more recent?

**Comment by ZoranRavic** [comment]
> ffmpeg-n4.3.2 and ffmpeg-N-101626 what`s the difference which branch is more recent?

ffmpeg-N includes the latest versions of third party libraries. I use that one.

If you have problems with ffmpeg-N then use ffmpeg-n4.3.2.

You can run `ffmpeg -version` to see the versions included in the build you have.

**Comment by BtbN** [comment]
All builds use the exact same set of libraries. Only the ffmpeg branch it's built from is different.

**Comment by ZoranRavic** [comment]
> All builds use the exact same set of libraries. Only the ffmpeg branch it's built from is different.

Then why when I run `ffmpeg -version` with ffmpeg-N and with ffmpeg-n4.3.2 it shows that (libavutil, etc..) aren't the same?

**Comment by BtbN** [comment]
Because libavutil is an ffmpeg library. Obviously its version is different between different ffmpeg versions.

**Comment by ZoranRavic** [comment]
Sorry, I was misinformed. Can You answer necros2k7's question then?

**Comment by BtbN** [comment]
Like I said, the ffmpeg branch it's built from is the only difference.
One is master, one is 4.3. Soon to be switched to 4.4.

**Comment by necros2k7** [comment]
So all recent commits go to master and it`s more recent right?

**Comment by oghaki** [comment]
I don't understand the differences either, and while I appreciate recommendations, an explanation of the reason for the recommendation is a lot more helpful (and would also help to answer the question OP asked).  I'd be curious about the following:
1. From an end-user standpoint, why would I prefer **LGPL** over **GPL** or vice versa?
2. What is the difference between the licenses suffixed with '**-shared**' versus the ones without?
3. Is there a reason to use the **Vulcan** version?  If so, does that relate to hardware encoding, decoding, both, or something else entirely?  If it does relate to encoding, is hardware encoding then mandatory or optional?

**Comment by nyonax** [comment]
1. The GPL package has more features than the LGPL package. However, since the GPL is a more restrictive license, compiling those pieces into ffmpeg also places more restrictions on how ffmpeg can be used. If you're using another application that is built on top of ffmpeg, or otherwise uses ffmpeg in some way, then you'll need to read both the GPL and LGPL to see which applies to your situation. But if you're just using ffmpeg by itself you can use either package, although you may want some of the features that are compiled into the GPL package.   

2. In this case **shared** means that ffmpeg was built with shared libraries, and those libraries are part of the supplied package. These are the ".a" and ".dll" files in the zip. You'll need this package if you're working with another application that can use ffmpeg's functionality by loading one of these libraries, or if you're building such an application. If that's the case, though, you'll also want to refer back to #1 and read the GPL and LGPL to see if you need to use the **-lgpl** package, or can use the **-gpl** package. If you're just using ffmpeg by itself you can use either the shared or regular package, but you may want to use the regular (i.e. not the **-shared** package) since there will be far fewer files to worry about.

3. I'm curious about this one as well. I haven't read much yet about Vulkan and wonder if it will be of general benefit with ffmpeg, or if there are any instances where it should be avoided.

**Comment by garoto** [comment]
And complementing the above about 1., below are the encoders (`ffmpeg -encoders`) not present on LGPL builds:

```diff
--- encode_GPL.txt      2021-03-26 15:46:28.075518200 -0300
+++ encode_LGPL.txt     2021-03-26 15:46:36.069004000 -0300
@@ -22 +21,0 @@
- V..... libxavs2             libxavs2 AVS2-P2/IEEE1857.4 (codec avs2)
@@ -44,2 +42,0 @@
- V..... libx264              libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (codec h264)
- V..... libx264rgb           libx264 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 RGB (codec h264)
@@ -52 +48,0 @@
- V..... libx265              libx265 H.265 / HEVC (codec hevc)
@@ -70 +65,0 @@
- V..... libxvid              libxvidcore MPEG-4 part 2 (codec mpeg4)
```

`avisynth` isn't supported as well.

**Comment by BtbN** [comment]
Vulkan only exists as separate build because their "dynamic" loader is very undynamic, and a binary built with Vulkan support won't work at all on a system without a working Vulkan driver, even if you don't ever want to use any of the Vulkan based filters. It'll just fail to launch, for lack of vulkan-1.dll.

Eventually FFmpeg will switch to an actual dynamic loader for Vulkan, eliminating the need for separate builds.

**Comment by garoto** [comment]
> What is the difference between the licenses suffixed with '-shared' versus the ones without?

`-shared` isn't about licenses, it's a software compilation thing-y: "shared mode" means all three windows binaries shipped with a ffmpeg compile (`ffmpe, ffprobe, ffplay`) are going to be just an ` .exe` wrapper around the binary libraries shipped inside the zip file (the  `.DLLs`). 

In a `static` build, all three ffmpeg companion programs mentioned above, will all have those same DLLs all baked into each, making their individual sizes to balloon unnecessarily large, since they all share the same code anyways.

**Comment by sudo-nautilus** [comment]
What about adding the description in the wiki ?

**Comment by sudo-nautilus** [comment]
Plus link wiki to the readme

**Comment by sudo-nautilus** [comment]
He added it in the Readme.md

**Comment by tormento** [comment]
Can you please explain me the difference between "4.4 to build from the 4.4 release branch instead of master."

And where has the Vulkan build gone? :)

**Comment by BtbN** [comment]
Not sure how else to explain that. It does exactly what it says, and builds from the 4.4 release branch, instead of master.

FFmpeg master now dynamically loads Vulkan, so the reason for separate builds is gone.
4.4 just plain does not have it enabled anymore.

**Comment by BtbN** [comment]
I hope the description of the variants is good enough now.
Haven't heard any complaints in a while, so I will close this issue.

**Comment by BtbN** [comment]
No, libnpp is nonfree.

**Comment by caublet** [comment]
IF I build myself nonfree-shared, libnpp will be included?

**Comment by BtbN** [comment]
No, since it's impossible to download libnpp without accepting an Nvidia EULA.

**Comment by caublet** [comment]
I'm new to this.. I'm trying to get  a version of ffmpeg that included libnpp for Frigate.. I requires this lib in go2rtc to rotate a stream using gpu. Anything to put me on track?
