### ISSUE TITLE
32bit builds

### ISSUE THREAD

**Issue by sh-navid** [BtbN/FFmpeg-Builds#61]
Hi :)

I can see in your README that there is 32bit version of FFmpeg

```
Targets, Variants and Addins
The two available targets are win64 and win32.
```

but in your official website and release link there is just 64bit versions
https://github.com/BtbN/FFmpeg-Builds/releases

Is there a 32bit official version?
If not, Is there an instruction to compile it myself?

**Comment by BtbN** [comment]
See the various other issues about that.
In short: There is no space for more variants, and due to 32bit being mostly dead, avoid users downloading needlessly slower 32bit builds and to use the space for more useful 64bit variants, there are no 64 bit pre-builts.

The builds scripts are perfectly capable of building a 32 bit variant, minus a bunch of dependencies that dropped 32bit support as well.
Just substitute win64 with win32 in the makeimage and build commands.

**Comment by sh-navid** [comment]
Ok, Thanks for the answer :)

**Comment by pzhlkj6612** [comment]
Hi @BtbN .

```diff
- ... there are no 64 bit pre-builts.
+ ... there are no 32 bit pre-builts.
```

:)

**Comment by sudo-nautilus** [comment]
you can check this for 32 bit build - https://github.com/sudo-nautilus/FFmpeg-Builds-Win32 
@BtbN , #59 - that one, please check it

**Comment by sh-navid** [comment]
> you can check this for 32 bit build - https://github.com/sudo-nautilus/FFmpeg-Builds-Win32
> @BtbN , #59 - that one, please check it

Thanks for sharing this :)

**Comment by BtbN** [comment]
I will not link to or in any sense officially endorse someone else's builds, since I can in no way guarantee that these binaries are trustworthy and properly maintained.
My recommendation would be to use 64bit builds instead. The list of reasons to use 32 bit builds is very short.

Adding "Win32" somewhere would only confuse people who got no idea about 64 vs. 32 bit, and cause users to download slower and less featureful binaries.
The list of downloads is already confusing enough as it is. Effectively doubling that up with everything being win32 vs. win64 is really not great.

**Comment by sh-navid** [comment]
@BtbN Thanks for your explanation :)
I understand as a programmer because I have a hard time trusting a repository; But unfortunately In a specific project, I had to use a 32-bit machine.

By the way, Cause I just want to mux sound with video, I finally decided to use an alternative library :)

**Comment by sudo-nautilus** [comment]
> I will not link to or in any sense officially endorse someone else's builds, since I can in no way guarantee that these binaries are trustworthy and properly maintained.
> My recommendation would be to use 64bit builds instead. The list of reasons to use 32 bit builds is very short.
> 
> Adding "Win32" somewhere would only confuse people who got no idea about 64 vs. 32 bit, and cause users to download slower and less featureful binaries.
> The list of downloads is already confusing enough as it is. Effectively doubling that up with everything being win32 vs. win64 is really not great.

Bruh
I can't use 64 bit one cuz I have 32 bit operating system. Anyway thanks

**Comment by bopoh13** [comment]
@sudo-nautilus thanks for trying to make an assembly under win7.
Unfortunately **h264** doesn't play a video if I compille it out of pictures. I don't know how to set [type pixels](20). I use [version 3.4.2](3#issuecomment-701170397).

**Comment by sudo-nautilus** [comment]
@bopoh13 you may try 4.4 version
