### ISSUE TITLE
Build doesn't work in docker rootless mode

### ISSUE THREAD

**Issue by phantom10111** [BtbN/FFmpeg-Builds#7]
Trying to make a build locally resulted in the following error:

```
+ docker run --rm -i -u 1000:1000 -v /home/phantom/FFmpeg-Builds/ffbuild:/ffbuild docker.pkg.github.com/btbn/ffmpeg-builds/win32-lgpl-shared:latest bash -s
+ cd /ffbuild
+ rm -rf ffmpeg prefix
+ git clone https://github.com/FFmpeg/FFmpeg.git ffmpeg
fatal: could not create work tree dir 'ffmpeg': Permission denied
```

Looks like the issue is that the commands inside the container are run with my own user id, when they should be run with user id 1. If I remove `-u "$(id -u):$(id -g)"` from `build.sh`, then the commands succeed. I'd send a pull request with this change, but I'm assuming there must be some significance to manually setting the user id in the script, otherwise the option wouldn't be there.

**Comment by BtbN** [comment]
Without running it as the same user/group than the one that's invoking the command causes issues later in the script, because build-artifacts end up owned by root.
Packaging artifacts and deleting leftovers fails then without doing so as root as well.
Since this is designed to run on Github-Actions, where dockerd runs as root, this cannot be changed and in turn means a setup where docker-root is not real root isn't supported.

I also don't really see any way to check if the uid dockerd runs as is identical to the one of the current user, which is the check necessary to drop the User-Switch.

**Comment by BtbN** [comment]
Please try again with latest changes.

**Comment by phantom10111** [comment]
Looks like it works now. Thank you very much for fixing.
