### ISSUE TITLE
32 bit builds for windows

### ISSUE THREAD

**Issue by MyTDT-Mysoft** [BtbN/FFmpeg-Builds#83]
please?

**Comment by sudo-nautilus** [comment]
Hi there,
Currently, 32 bit autobuilds are disabled in this repository for some reason. However you can build it. If you want to download them, check my repository below.

https://github.com/sudo-nautilus/FFmpeg-Builds-Win32

**Comment by BtbN** [comment]
Explained that multiple times already. There is limited asset space available, and I'd rather use that for more useful things than 32bit builds.
And it would also get a bunch of unknowing users to download the 32bit build, not realizing what that means, and missing out on a bunch of performance, features, and compiler side hardening.

The use of 32bit in 2021 is close to 0. If you really have an ultra niche scenario where you need it, you can run the build setup manually and make it produce 32bit binaries. But keep in mind that this is untested, and can randomly break on updates.
Opening issues or sending fixes if that happens is absolutely valid though.

**Comment by garoto** [comment]
> 32 bit autobuilds are disabled in this repository for _some reason_.

Just disable the issue tracker at this point.

**Comment by tomasz1986** [comment]
> The use of 32bit in 2021 is close to 0.

Just for the record, there is still a tonne of Intel Atom devices (i.e. mainly netbooks and tablets) in use today which were produced between mainly between 2012-2018 that use 32-bit UEFI. All of them came with Windows x86 by default, and are incapable of running Windows x64 whatsoever.

They may be niche for geeks who are used to very powerful desktop machines, but were and still are quite common among "normal" computer users. Granted, most of those shouldn't have been manufactured in the first place (due to their horrible performance), but this is the reality.

I personally wouldn't be surprised if Windows x86 worldwide market share is still higher than desktop Linux (regardless of the architecture).

**Comment by sudo-nautilus** [comment]
> > The use of 32bit in 2021 is close to 0.
> 
> Just for the record, there is still a tonne of Intel Atom devices (i.e. mainly netbooks and tablets) in use today which were produced between mainly between 2012-2018 that use 32-bit UEFI. All of them came with Windows x86 by default, and are incapable of running Windows x64 whatsoever.




But according to this - https://www.microsoft.com/en-in/windows/windows-11

Windows will no longer be available in x86 platform (I guess). But anyway I'll continue to maintain [my repo](https://github.com/sudo-nautilus/FFmpeg-Builds-Win32) which builds FFmpeg for x86 windows (yes, it's based on this code) to a certain extent.

**Comment by tomasz1986** [comment]
> Windows will no longer be available in x86 platform (I guess).

Yeah, but there is still a very long way to go. At the moment, even Windows 8.1 x86 is still supported and receives updates, and when it comes to Windows 10, the x86 version of the last LTSC 2019 is going to be supported until 2029.

And thank you very much for the builds 🙂.

**Comment by sudo-nautilus** [comment]
> > Windows will no longer be available in x86 platform (I guess).
> 
> Yeah, but there is still a very long way to go. At the moment, even Windows 8.1 x86 is still supported and receives updates, and when it comes to Windows 10, the x86 version of the last LTSC 2019 is going to be supported until 2029.
> 

Hmm

> And thank you very much for the builds 🙂.

You are welcome 😸
