### ISSUE TITLE
Mabey add build dates ?

### ISSUE THREAD

**Issue by spiralfeel** [BtbN/FFmpeg-Builds#87]
Like next to the version when viewed in command line 
example 
"ffmpeg version N-102790-g947122f111 Copyright..." to 
"ffmpeg version N-102790-g947122f111 build 2021-01-01 Copyright..."
Not that it's very important, it would just be easier to see at first glance how old is the version I'm using :)

**Comment by BtbN** [comment]
I can't really influence what ffmpeg prints in its header.
And so far I decided against adding it to the archive name, since it's already pretty long and convoluted as it is.

You can take the commit hash it prints there (947122f111 in this case), plug it into https://github.com/FFmpeg/FFmpeg/commit/947122f111 and get a date that way.

I'll check if ffmpeg can be made to include a build date in some kind of custom version.

**Comment by garoto** [comment]
Apparently, cloning the repository with `--depth 1` makes ffmpeg use the compile date + commit hash as version identifier:

>\> ffmpeg -version
>ffmpeg version git-2021-04-13-33db0cbf Copyright (c) 2000-2021 the FFmpeg developers

It can be seen in mpv Windows buids by shinchiro.

**Comment by BtbN** [comment]
Yes, because it becomes unable to determine the proper version slug, which is counting commits.
That version number is mandatory for a lot of things, so not having it is not a good idea.

**Comment by garoto** [comment]
Ah ok.
