### ISSUE TITLE
Adding ffmpeg plus opengl

### ISSUE THREAD

**Issue by FluffyDiscord** [BtbN/FFmpeg-Builds#89]
Hi, would it be possible to add this extension to the build ?

https://github.com/numberwolf/FFmpeg-Plus-OpenGL/blob/main/README_EN.MD

**Comment by BtbN** [comment]
That looks like a 3rd party patch-set for ffmpeg?
If so, that's not something I'm willing to add, since it's not a simple dependency of ffmpeg.
Every single patch to ffmpeg potentially breaks it, and it's not at all tested by the ffmpeg project itself.

Something like this should be sent upstream to FFmpeg so it can be included in the official sources.

**Comment by FluffyDiscord** [comment]
It is 3rd party patch. A shame, but what can we do.
