### ISSUE TITLE
Possible windows x86 build??

### ISSUE THREAD

**Issue by kedaitinh12** [BtbN/FFmpeg-Builds#96]
Can you add x86 ver for ffmpeg??

**Comment by BtbN** [comment]
See https://github.com/BtbN/FFmpeg-Builds/issues/83 and https://github.com/BtbN/FFmpeg-Builds/issues/12 and a bunch of other similar issues.
You can build 32 bit yourself with the scripts if you really need it, but generally, you should be using 64bit.

To repeat myself again: 32bit would waste asset space and would result in other more useful builds to be removed.
Plus, a whole bunch of people would download the 32bit builds because they just don't know better, and end up with a slower build and missing features.

**Comment by kedaitinh12** [comment]
Thanks for reply
